name: Build lindale-ui
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install
      run: npm install
    - name: build
      working-directory: demo
      run: npm run build
